import Vue from 'vue'
import {library, config} from '@fortawesome/fontawesome-svg-core'

import {
  logo,
  courses,
  achievements,
  homework,
  notifications,
  bell,
  play,
  exit,
  rating,
  members,
  views,
  arrowLeft,
  questionSign,
  copy,
  mail,
  clock,
  git,
  downArrow,
  eye,
  clipboard,
  checkCircle,
  fileText,
  playSample,
  close,
  arrowRight,
  kotlin,
  androidStudio,
  sbLock,
  chevronLeft,
  deadline,
  like,
  queue,
  archive,
  checkAll,
  codeReview,
  rocket,
  calendar,
  level,
  wallet,
  dislike,
  link,
  collapse,
  compress,
  salePercent,
  android,
  presentation,
  telegram,
  grphql,
  rx,
  firebase,
  mlkit,
  github,
  star, dart,
  redux,
  vscode,
  apple,
  flutter,
  moon,
  sun,
  pause,
  skillPoints,
  tooltipIcon,
  userProfile,
  nextLesson,
  prevLesson,
  vk,
  facebook,
    rightWay,
    yaDzen,
    socialMedium,
    reddit,
    linkedIn,
    youtube,
    twitter
} from './custom/custom-icons'
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'

config.autoAddCss = false
config.searchPseudoElements = true;
// FontAwesomeIcon.dom.i2svg();

library.add(
    deadline,
    logo, courses, achievements, homework, notifications, bell, play, exit, rating, members, views, arrowLeft, questionSign, copy, mail,
    git, downArrow, eye, clipboard, checkCircle, playSample, clock, close, arrowRight, kotlin, androidStudio, sbLock, chevronLeft, like, queue, archive, checkAll, codeReview,
    rocket, calendar, level, wallet, dislike, link, compress, collapse, salePercent, presentation, telegram, grphql,
    rx,
    firebase,
    mlkit,
    github,
    android,
    star,
    dart,
    redux,
    vscode,
    apple,
    flutter,
    moon,
    sun,
    pause,
    skillPoints,
    tooltipIcon,
    userProfile,
    fileText,
    nextLesson,
    prevLesson,
    vk,
    facebook,
    rightWay,
    yaDzen,
    socialMedium,
    reddit,
    linkedIn,
    youtube,
    twitter
);

Vue.component('fa-icon', FontAwesomeIcon)

// Vue.config.productionTip = false
